### ISSUE TITLE
Prevent newlines to be added inside a <textarea> element

### ISSUE THREAD

**Issue by electrotype** [trivago/prettier-plugin-twig-melody#107]
I see this plugin doesn't seem to be maintained anymore, but in case someone knows how to fix my issue:

Using `parser: "melody"` on my HTML files will add newlines inside `<textarea>` elements. For example:

```
<textarea>{{ myValue }}</textarea>
```
will become:
```
<textarea>
  {{ myValue }}
</textarea>
```

Of course this is not desired, as the newlines are then visible to the user in the textareas.

Any options/idea on how to fix this?

**Comment by karlschwaier** [comment]
Yes, that's easy to fix with Twig's whitespace control, see https://twig.symfony.com/doc/3.x/templates.html#whitespace-control. 

```
<textarea>
  {{- myValue -}}
</textarea>
```

**Comment by electrotype** [comment]
I didn't know that trick, it works! Thanks!
