### ISSUE TITLE
Plugin removes final newline

### ISSUE THREAD

**Issue by urbantrout** [trivago/prettier-plugin-twig-melody#2]
I have a `.editorconfig` file with:
```
insert_final_newline = true
```

This plugin removes final newlines in all of my twig files.

Expected behavior:
- Respect the settings in `.editorconfig` and do not remove the final newline.

**Comment by twbartel** [comment]
Looking into it, stay tuned.

**Comment by twbartel** [comment]
I had a look at the Prettier source code, and Prettier itself seems only to support certain properties from `.editorconfig`: quote_type, tab_width, indent_style, indent_size, max_line_length, end_of_line.

I could not find `insert_final_newline`. Therefore, if Prettier does not pass this option through to my plugin, I cannot (should not?) take it into account.

What I will do, however, is leave _one_ final newline in place (or add it, if it's not there) as the default behaviour. Would that be ok for you?

**Comment by twbartel** [comment]
I just published v0.0.28 which always appends a newline. Can you give it a try?

**Comment by urbantrout** [comment]
It works. Thanks!
