### ISSUE TITLE
Bug: String concatenation

### ISSUE THREAD

**Issue by chasegiunta** [trivago/prettier-plugin-twig-melody#20]
`{% include 'foo/' ~ bar %}`
will output:
`{% include ''foo/' ~ bar' %}` (singleQuotes true)
`{% include ""foo/" ~ bar" %}` (singleQuotes false)

**Comment by twbartel** [comment]
Nice find, thanks! Just fixed it in master, will release later.

**Comment by twbartel** [comment]
Released as part of `v0.2.2`. Can you check?

**Comment by chasegiunta** [comment]
Seems to be working great! Thanks!
