### ISSUE TITLE
Prevent adding block name to endblock

### ISSUE THREAD

**Issue by zebapy** [trivago/prettier-plugin-twig-melody#22]
I see `endblock` is getting the opening block name appended after it like so

```twig
{% block layout_header %}
  {% include 'partials/school-header.twig' %}
{% endblock layout_header %}
```

I prefer NOT having the closing name
```twig
{% block layout_header %}
  {% include 'partials/school-header.twig' %}
{% endblock  %}
```

Is there a way to control this? I didn't see it as part of the twig coding standards.

**Comment by twbartel** [comment]
Thanks for your input. I agree, it does not always look good to have the name repeated there.

I have added an option `twigOutputEndblockName` and set its default to `false`. You should now not get the block name in the `endblock` tag any more. 
Please upgrade to `v0.3.0`.

**Comment by zebapy** [comment]
Whoa thanks for the fast implementation! 👍 👍 `0.3.0` works great.

**Comment by twbartel** [comment]
You're welcome! Glad to hear it works.
