### ISSUE TITLE
Bug: single/double quote conversion breaks with strings containing quotes

### ISSUE THREAD

**Issue by chasegiunta** [trivago/prettier-plugin-twig-melody#24]
Here's an example to make sense of:
```
{% set teamName = teamName|replace("College - Women's", "- Women's") %}
```
will format to
```
{% set teamName = teamName | replace('College - Women's', '- Women's') %}
```

The apostrophe in `Women's` is breaking our formatting here. Is it possible to detect `'` or `"`characters inside our quotes and ignore the quote conversion, similar to how the detection is done in #21 with `#{` and double quotes?

**Comment by twbartel** [comment]
Hey Chase, thanks, will take a look.

**Comment by twbartel** [comment]
There is a fix in `v0.3.1`. Can you have a look?

**Comment by chasegiunta** [comment]
@twbartel That works, thanks!

Worth noting for future references that for those of us using VS Code, after updating prettier-plugin-twig-melody, VS Code needs a full restart to start using the updated version.

**Comment by twbartel** [comment]
Yeah, I noticed that, too. It's a bit annoying.
