### ISSUE TITLE
Prettier globally installed issue

### ISSUE THREAD

**Issue by LouisCuvelier** [trivago/prettier-plugin-twig-melody#36]
Hi,

I tried to use this plugin with Prettier installed globally. The folder is `~/.config/yarn/global/` and my .prettierrc.js is in it. Here's the config :
```js
module.exports = {
  twigMultiTags: [
    "nav,endnav",
    "switch,case,default,endswitch",
    "ifchildren,endifchildren",
    "cache,endcache"
  ]
};
```

I did the command `prettier --write "**/*.twig"` and it returned `Could not load plugin path ~/.config/yarn/global/node_modules/prettier-twig-craft-cms`

I also tried to specify in the config the plugin path, but it changes nothing.

Any clue ?

**Comment by chasegiunta** [comment]
@LouisCuvelier the `prettier-twig-craft-cms` package that @twbartel was experimenting with is not one you'd want to use. I haven't tried installing `prettier-plugin-twig-melody` globally, but using _this_ package locally to the project should work.

**Comment by LouisCuvelier** [comment]
Oh ... shame on me. Sorry for the waste of time ...
Moreover, after a rebooting, everything is working fine now 😄

**Comment by twbartel** [comment]
Thanks @chasegiunta for taking care!
