### ISSUE TITLE
Support for <script> and <style> tags?

### ISSUE THREAD

**Issue by Epskampie** [trivago/prettier-plugin-twig-melody#71]
Would love to use this, but a lot of our twig files have inline css and/or scripts like so:

```html
<style>
    .foobar { 
        text-align: right;
    }
</style>

<script>
    console.log('hello, world');
</script>
```

Right now this plugin treats the content as text, concatenating a lot of it. Ideally it would use the default prettier formatters for CSS and js for these parts, but if it would just leave them alone (no change in formatting) that would also be acceptable.

Is anything like this planned?

**Comment by rastko909** [comment]
Also have the same issue on a couple repos, is there a work around for this other than ignoring files?
