### ISSUE TITLE
FR: prettier-ignore lines

### ISSUE THREAD

**Issue by chasegiunta** [trivago/prettier-plugin-twig-melody#9]
Since this plugin is very much still a WIP (appreciate all your hard work on this!) if we run across some code blocks/lines that aren't currently working well with prettier-plugin-twig-melody, it would be great to disable those lines with `prettier-ignore` comments like we can in other languages that prettier supports.

https://prettier.io/docs/en/ignore.html#html

**Comment by twbartel** [comment]
Hi Chase, thanks for your suggestions and bug reports! I will look into them.

**Comment by twbartel** [comment]
Hi @chasegiunta, I just published version 0.2.0 which adds `prettier-ignore` functionality. Have a look when you have time.

**Comment by chasegiunta** [comment]
This seems to be working great!
